name: jpa-learn-demo

services:
    jpa-learning-demo-postgres:
        image: postgres:12.10
        container_name: jpa-learning-demo-postgres
        ports:
            - "5433:5432"
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: jpa-learn-demo
        volumes:
            - jpa-learning-demo-postgres-data:/var/lib/postgresql/data
        networks:
            - jpa-learn-demo-network


volumes:
    jpa-learning-demo-postgres-data:

networks:
    jpa-learn-demo-network:
        external: true
        driver: bridge
