name: jpa-learn-demo

services:
    jpa-learn-demo-postgres:
        image: postgres:13
        container_name: jpa-learn-demo-postgres
        ports: [ "5433:5432" ]
        restart: always
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 10s
            timeout: 5s
            retries: 5
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: jpa-learn-demo
        volumes: [ "jpa-learn-demo-postgres-data:/var/lib/postgresql/data" ]
        networks: [ "jpa-learn-demo-network" ]

    jpa-learn-demo-pgadmin:
        image: dpage/pgadmin4
        container_name: jpa-learn-demo-pgadmin
        restart: always
        ports: [ "5050:80" ]
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:80" ] # 或者其他端口和路径
            interval: 30s
            timeout: 10s
            retries: 3
        volumes: [ "jpa-learn-demo-pgadmin-data:/var/lib/pgadmin" ]
        networks: [ "jpa-learn-demo-network" ]

volumes:
    jpa-learn-demo-postgres-data:
    jpa-learn-demo-pgadmin-data:

networks:
    jpa-learn-demo-network:
        external: true
        name: jpa-learn-demo-network